embed_assets: off

javascripts:
  uploadify:
    - public/javascripts/uploadify.214.js
    - public/javascripts/uploadify.swfobject.js

stylesheets:
  application:
    - public/stylesheets/application.css
